# Generated by Django 5.2.4 on 2025-07-13 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="پست الکترونیک"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="نام کاربری",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="0",
                        max_length=12,
                        unique=True,
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="UserImage",
                        verbose_name="عکس کاربر",
                    ),
                ),
                (
                    "Full_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نام کامل"
                    ),
                ),
                (
                    "is_Accept_terms",
                    models.BooleanField(default=False, verbose_name="پذیرفتن شرایط"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("is_admin", models.BooleanField(default=False, verbose_name="ادمین")),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربر ها",
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=12, null=True)),
                ("phone", models.CharField(max_length=12)),
                ("code", models.SmallIntegerField(blank=True, null=True)),
                ("expiration_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "کد:otp",
                "verbose_name_plural": "کد:otp ها",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="ادرس"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                ("phone", models.CharField(max_length=12, verbose_name="تلفن")),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ادرس",
                "verbose_name_plural": "تنظیمات قسمت ادرس",
            },
        ),
    ]
