# Generated by Django 5.2.4 on 2025-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام کاربری"
            ),
        ),
    ]
