# Generated by Django 5.2.4 on 2025-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=550, null=True, verbose_name="نام شهر"),
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=550, null=True, verbose_name="نام کشور"),
        ),
        migrations.AddField(
            model_name="address",
            name="province",
            field=models.CharField(max_length=550, null=True, verbose_name="نام استان"),
        ),
    ]
