# Generated by Django 5.2.4 on 2025-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_address_city_address_country_address_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="next_page",
            field=models.TextField(blank=True, null=True),
        ),
    ]
