# Generated by Django 5.2.4 on 2025-07-15 12:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUsMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=2500, verbose_name="تییتر توضیحات"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="about/images/", verbose_name="تصویر"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "توضیح",
                "verbose_name_plural": "توضیحات",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ConjuctionPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=3500, verbose_name="نام")),
                ("year", models.BigIntegerField(default=0, verbose_name="سال")),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="توضیحات"
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "نقطه عطف",
                "verbose_name_plural": "نقاط عطف",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ShopAttr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2500, verbose_name="نام ویژگی")),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="about/images/", verbose_name="تصویر"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ویژگی سایت",
                "verbose_name_plural": "ویژگی های سایت",
                "ordering": ("-created",),
            },
        ),
    ]
