# Generated by Django 5.2.4 on 2025-07-14 08:28

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-created",),
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقاله ها",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "تگ", "verbose_name_plural": "تگ ها"},
        ),
        migrations.AlterModelOptions(
            name="tip",
            options={"verbose_name": "نکته", "verbose_name_plural": "نکته ها"},
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                related_name="articles_cate",
                to="blog.category",
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="discription",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.FileField(upload_to="blog/image/", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_publish",
            field=models.BooleanField(default=True, verbose_name="نمایش داده شود"),
        ),
        migrations.AlterField(
            model_name="article",
            name="little_discription",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات کوتاه"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(
                related_name="article_tag", to="blog.tag", verbose_name="تگ"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tip",
            field=models.ManyToManyField(
                related_name="article_tip", to="blog.tip", verbose_name="نکته"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                max_length=2500, null=True, verbose_name="نام مقاله"
            ),
        ),
    ]
