# Generated by Django 5.2.4 on 2025-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tip",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="article_tip",
                to="blog.tip",
                verbose_name="نکته",
            ),
        ),
    ]
