# Generated by Django 5.2.4 on 2025-07-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_article_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="blog/video/", verbose_name="ویدیو"
            ),
        ),
    ]
