# Generated by Django 5.2.4 on 2025-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2500, verbose_name="نام")),
                ("phone", models.BigIntegerField(default=0, verbose_name="شماره تلفن")),
                ("sub_title", models.CharField(max_length=3500, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="پیام")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "تماس با ما",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.BigIntegerField(default=0, verbose_name="شماره تلفن")),
                (
                    "support",
                    models.CharField(
                        help_text="شماره تلفن یا ایمیل",
                        max_length=2500,
                        verbose_name="پشتیبانی مشتری",
                    ),
                ),
                (
                    "sell_support",
                    models.CharField(
                        help_text="شماره تلفن یا ایمیل",
                        max_length=2500,
                        verbose_name="پشتیبانی فروش",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "اطلاعات تماس",
                "verbose_name_plural": "اطلاعات تماس",
                "ordering": ("-created",),
            },
        ),
    ]
