# Generated by Django 5.2.4 on 2025-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
