# Generated by Django 4.2.23 on 2025-07-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_contactinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='شماره تلفن'),
        ),
    ]
