# Generated by Django 5.2.4 on 2025-07-13 21:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=2500, verbose_name="موضوع یا تیتر پوستر"
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات بیشتر"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="home/images/", verbose_name="تصویر پوستر"
                    ),
                ),
                ("link", models.TextField(verbose_name="لینک موردنظر")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "پوستر",
                "verbose_name_plural": "پوستر ها",
                "ordering": ("-created",),
            },
        ),
    ]
