# Generated by Django 5.2.4 on 2025-07-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=550, verbose_name="نام برند")),
                (
                    "image",
                    models.ImageField(
                        upload_to="home/images/", verbose_name="تصویر برند"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برند ها",
                "ordering": ("-created",),
            },
        ),
    ]
