# Generated by Django 5.2.4 on 2025-07-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.FileField(upload_to="home/images/", verbose_name="تصویر برند"),
        ),
    ]
