# Generated by Django 5.2.4 on 2025-07-14 06:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_brand_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=1500, verbose_name="تیتر یا نام ویژگی"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات بیشتر"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="home/images/",
                        verbose_name="تصویر مورد نظر برای این ویژگی",
                    ),
                ),
                ("link", models.TextField(verbose_name="لینک مورد نظر")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی های سایت",
                "ordering": ("-created",),
            },
        ),
    ]
