# Generated by Django 5.2.4 on 2025-07-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_attr"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attr",
            new_name="LittlePoster",
        ),
        migrations.AlterModelOptions(
            name="littleposter",
            options={
                "ordering": ("-created",),
                "verbose_name": "پوستر",
                "verbose_name_plural": "پوستر های تبلیفانی کوچکتر",
            },
        ),
    ]
