# Generated by Django 5.2.4 on 2025-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_attr_littleposter_alter_littleposter_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopAttr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1500, verbose_name="نام ویژگی")),
                (
                    "image",
                    models.FileField(upload_to="home/images/", verbose_name="تصویر"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ویژگی وبسایت",
                "verbose_name_plural": "ویژگی های وبسایت",
                "ordering": ("-created",),
            },
        ),
    ]
