# Generated by Django 5.2.4 on 2025-07-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_shopattr"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(verbose_name="ادرس ایکون شبکه اجتماعی")),
                ("link", models.TextField(verbose_name="لینک شبکه اجتماعی")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "لینک شبکه اجتماعی",
                "verbose_name_plural": "لینک شبکه های اجتماعی",
                "ordering": ("-created",),
            },
        ),
    ]
