# Generated by Django 5.2.4 on 2025-07-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_socialmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="سوالات")),
                ("answer", models.TextField(verbose_name="جواب سوال")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوالات متداول",
                "ordering": ("-created",),
            },
        ),
    ]
