# Generated by Django 5.2.4 on 2025-07-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "باشگاه مشتریان",
                "verbose_name_plural": "باشگاه مشتریان",
                "ordering": ("-created",),
            },
        ),
    ]
