# Generated by Django 5.2.4 on 2025-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_customerclub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerclub",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
    ]
