# Generated by Django 5.2.4 on 2025-07-15 12:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_customerclub_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopattr",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default=1, verbose_name="توضیحات"
            ),
            preserve_default=False,
        ),
    ]
