# Generated by Django 5.2.4 on 2025-07-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_shopattr_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerclub",
            name="email",
        ),
        migrations.AddField(
            model_name="customerclub",
            name="phone",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
