# Generated by Django 5.2.4 on 2025-07-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_remove_customerclub_email_customerclub_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(upload_to="home/video/", verbose_name="ویدیو"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ویدیو",
                "verbose_name_plural": "ویدیو ها",
                "ordering": ("-created",),
            },
        ),
    ]
