# Generated by Django 5.2.4 on 2025-07-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2500, verbose_name="تیتر بنر")),
                (
                    "image",
                    models.FileField(upload_to="home/banner/", verbose_name="تصویر"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنر ها",
                "ordering": ("-created",),
            },
        ),
    ]
