# Generated by Django 5.2.4 on 2025-07-23 03:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="توضیحات"
                    ),
                ),
            ],
            options={
                "verbose_name": "قانون",
                "verbose_name_plural": "قوانین",
            },
        ),
    ]
