# Generated by Django 4.2.23 on 2025-07-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='color',
            field=models.TextField(default=1, verbose_name='رنگ شبکه اجتماعی'),
            preserve_default=False,
        ),
    ]
