# Generated by Django 5.2.4 on 2025-07-15 11:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=1500, verbose_name="نام سر دسته"),
                ),
                (
                    "image",
                    models.FileField(upload_to="shop/images/", verbose_name="تصویر"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "سر دسته",
                "verbose_name_plural": "سر دسته ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=1500, verbose_name="نام دسته بندی"),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_parent",
                        to="shop.categoryparent",
                        verbose_name="سر دسته",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1500, verbose_name="نام کالا")),
                (
                    "english_title",
                    models.CharField(max_length=1500, verbose_name="نام اینگلیسی کالا"),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "price",
                    models.BigIntegerField(
                        default=0, verbose_name="قیمت کالا به تومان"
                    ),
                ),
                (
                    "discount_percent",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="درصد تخفبف"
                    ),
                ),
                (
                    "new_price",
                    models.BigIntegerField(
                        blank=True,
                        help_text="(این فیلد نیاز به پر شدن ندارد)",
                        null=True,
                        verbose_name="قیمت تخفیف خورده",
                    ),
                ),
                (
                    "little_content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="توضیحات کوتاه"
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="توضیحات کامل"
                    ),
                ),
                (
                    "ingredients",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="مواد تشکیل دهنده"
                    ),
                ),
                (
                    "how_to_user",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="نحوه استفاده"
                    ),
                ),
                (
                    "image1",
                    models.FileField(
                        upload_to="shop/images/", verbose_name="تصویر کالا"
                    ),
                ),
                (
                    "image2",
                    models.FileField(
                        upload_to="shop/images/", verbose_name="تصویر کالا"
                    ),
                ),
                (
                    "image3",
                    models.FileField(
                        upload_to="shop/images/", verbose_name="تصویر کالا"
                    ),
                ),
                ("value", models.BigIntegerField(default=0, verbose_name="اندازه")),
                ("inventory", models.BigIntegerField(default=0, verbose_name="موجودی")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="category_product",
                        to="shop.category",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کالا",
                "verbose_name_plural": "کالاها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_comment",
                        to="shop.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرها",
                "ordering": ("-created",),
            },
        ),
    ]
