# Generated by Django 5.2.4 on 2025-07-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_product",
                to="shop.categoryparent",
                verbose_name="سر دسته",
            ),
        ),
    ]
