# Generated by Django 5.2.4 on 2025-07-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_image4_product_image5_product_image6_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="how_to_user",
            new_name="how_to_use",
        ),
    ]
