# Generated by Django 5.2.4 on 2025-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_rename_how_to_user_product_how_to_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_count",
            field=models.BigIntegerField(
                default=0,
                help_text="نیاز به پر کردن این بهش نیست",
                verbose_name="تعداد فروش رفته",
            ),
        ),
    ]
