# Generated by Django 5.2.4 on 2025-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_sale_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="speacial",
            field=models.BooleanField(default=True, verbose_name="محصول خاص"),
        ),
    ]
