# Generated by Django 5.2.4 on 2025-07-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_product_speacial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.BooleanField(default=False, verbose_name="تخفیف"),
        ),
    ]
