# Generated by Django 5.2.4 on 2025-07-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_test",
            field=models.BigIntegerField(
                blank=True,
                help_text="نباید پر شود",
                null=True,
                verbose_name="درصد تخفبف",
            ),
        ),
    ]
