# Generated by Django 5.2.4 on 2025-07-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_discount_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timer", models.TimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "زمان شمار برای محصولات ویژه",
                "verbose_name_plural": "زمان شمار برای محصولات ویژه",
                "ordering": ("-created",),
            },
        ),
    ]
