# Generated by Django 5.2.4 on 2025-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("-created",),
                "verbose_name": "علاقه",
                "verbose_name_plural": "علاقه مندی ها",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_test",
            field=models.BigIntegerField(
                blank=True,
                help_text="لطفا تکرار شود",
                null=True,
                verbose_name="درصد تخفبف",
            ),
        ),
    ]
