# Generated by Django 5.2.4 on 2025-07-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_favorite_options_alter_product_discount_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="like_count",
            field=models.BigIntegerField(default=0, verbose_name="تعداد لایک ها"),
        ),
    ]
