# Generated by Django 5.2.4 on 2025-07-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_product_like_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=550, verbose_name="رنگ")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ ها",
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="product_color",
                to="shop.color",
                verbose_name="رنگ ها",
            ),
        ),
    ]
