# Generated by Django 5.2.4 on 2025-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_color_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="post_price",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="قیمت پسنت کالا به تومان"
            ),
        ),
    ]
