# Generated by Django 5.2.4 on 2025-08-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_product_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="درصد تخفبف"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_test",
            field=models.BigIntegerField(
                blank=True,
                default=0,
                help_text="لطفا تکرار شود",
                verbose_name="درصد تخفبف",
            ),
        ),
    ]
