# Generated by Django 5.2.4 on 2025-08-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_product_discount_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="درصد تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_test",
            field=models.BigIntegerField(
                blank=True,
                default=0,
                help_text="لطفا تکرار شود",
                verbose_name="درصد تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="english_title",
            field=models.CharField(max_length=1500, verbose_name="نام انگلیسی کالا"),
        ),
        migrations.AlterField(
            model_name="product",
            name="post_price",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="قیمت پست کالا به تومان"
            ),
        ),
    ]
