# Generated by Django 5.2.4 on 2025-08-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_product_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory_view",
            field=models.BigIntegerField(default=0, verbose_name="موجودی برای نمایش"),
        ),
        migrations.AddField(
            model_name="product",
            name="wieght",
            field=models.BigIntegerField(default=0, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shop/images/",
                verbose_name="تصویر کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shop/images/",
                verbose_name="تصویر کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shop/images/",
                verbose_name="تصویر کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image4",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shop/images/",
                verbose_name="تصویر کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image5",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shop/images/",
                verbose_name="تصویر کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image6",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shop/images/",
                verbose_name="تصویر کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="value",
            field=models.CharField(max_length=550, verbose_name="اندازه"),
        ),
    ]
