# Generated by Django 5.2.4 on 2025-08-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_product_inventory_view_product_wieght_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="product",
            name="wieght",
            field=models.BigIntegerField(
                default=0, help_text="گرم", verbose_name="وزن"
            ),
        ),
    ]
