# Generated by Django 5.2.4 on 2025-08-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_color_quantity_alter_product_wieght"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="title",
            field=models.CharField(
                blank=True, max_length=550, null=True, verbose_name="نام اصلی"
            ),
        ),
    ]
