# Generated by Django 5.2.4 on 2025-08-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_color_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=550, null=True, verbose_name="نام اصلی"
                    ),
                ),
                ("value", models.CharField(max_length=550, verbose_name="حجم")),
                ("quantity", models.IntegerField(default=0, verbose_name="تعداد")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ ها",
                "ordering": ("-created",),
            },
        ),
    ]
