# Generated by Django 5.2.4 on 2025-08-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="value",
            options={
                "ordering": ("-created",),
                "verbose_name": "حجم",
                "verbose_name_plural": "حجم ها",
            },
        ),
    ]
