# Generated by Django 5.2.4 on 2025-08-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_alter_value_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="value_product",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="product_value",
                to="shop.value",
                verbose_name="حجم ها",
            ),
        ),
    ]
