# Generated by Django 5.2.4 on 2025-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_product_value_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=550, null=True, verbose_name="نام اصلی"
                    ),
                ),
                ("size", models.CharField(max_length=550, verbose_name="سایز")),
                ("quantity", models.IntegerField(default=0, verbose_name="تعداد")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "حجم",
                "verbose_name_plural": "حجم ها",
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="product_size",
                to="shop.size",
                verbose_name="سایز ها",
            ),
        ),
    ]
