# Generated by Django 4.2.23 on 2025-08-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_size_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('-created',), 'verbose_name': 'سایز', 'verbose_name_plural': 'سایز ها '},
        ),
    ]
