# Generated by Django 4.2.23 on 2025-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='upload_to', verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='upload_to', verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='upload_to', verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='upload_to', verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to='upload_to', verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.FileField(blank=True, null=True, upload_to='upload_to', verbose_name='تصویر کالا'),
        ),
    ]
