# Generated by Django 4.2.23 on 2025-08-18 18:50

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر کالا'),
        ),
    ]
