# Generated by Django 5.2.4 on 2025-07-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_address_city_address_country_address_province"),
        ("shop", "0014_product_like_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام کد تخفیف"
                    ),
                ),
                (
                    "discount",
                    models.SmallIntegerField(default=0, verbose_name="مقدار درصد تفیف"),
                ),
                (
                    "quantity",
                    models.SmallIntegerField(default=1, verbose_name="تعداد کد تخفیف"),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "تنظیمات قسمت  کد های تخفیف",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.IntegerField(default=0, verbose_name="قیمت کلی"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_pay",
                    models.BooleanField(
                        default=False, verbose_name="ایا پرداخت شده است ؟"
                    ),
                ),
                (
                    "image_payed",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pay/image",
                        verbose_name="عکس پرداخت موفق",
                    ),
                ),
                (
                    "DeliveryDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تحویل محصول"
                    ),
                ),
                (
                    "addresses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_address",
                        to="account.address",
                        verbose_name="آدرس کاربر",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت درخواست خرید",
                "verbose_name_plural": "تنظیمات قسمت ثبت درخواست خرید ها",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.SmallIntegerField(verbose_name="تعداد")),
                ("price", models.PositiveIntegerField(verbose_name="قیمت")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.order",
                        verbose_name="کالا درحال انجام",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "پایان ثبت درخواست خرید",
                "verbose_name_plural": "تنظیمات قسمت  پایان ثبت درخواست خرید ها",
            },
        ),
    ]
