# Generated by Django 5.2.4 on 2025-07-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(
                blank=True, max_length=550, null=True, verbose_name="رنگ"
            ),
        ),
    ]
