# Generated by Django 5.2.4 on 2025-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_orderitem_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="post_price",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="هزینه پست"
            ),
        ),
    ]
