# Generated by Django 5.2.4 on 2025-07-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_remove_orderitem_post_price_order_post_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="post_price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="post_price",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="هزینه پست"
            ),
        ),
    ]
