# Generated by Django 5.2.4 on 2025-07-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_remove_order_post_price_orderitem_post_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="post_price",
            field=models.IntegerField(default=0, verbose_name="هزینه پست"),
        ),
    ]
