# Generated by Django 5.2.4 on 2025-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_order_post_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="value",
            field=models.CharField(
                blank=True, max_length=550, null=True, verbose_name="حجم"
            ),
        ),
    ]
