# Generated by Django 5.2.4 on 2025-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_orderitem_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(
                blank=True, max_length=550, null=True, verbose_name="سایز"
            ),
        ),
    ]
